version: '2.1'

services: 
    # tracker_facade:
    # tracker_enricher:
    # tracker_payloads_keeper:
    zk:
        image: zookeeper:3.4.9
        hostname: zookeeper
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2128
            ZOO_SERVICES: server.1=zk.2888:3888
            ZOO)LOG4J_PROP: WARN
        # networks: 
        #     net:
        #         ipv4_address: 172.28.1.7
        logging:
            driver: none

    kafka:
        image: confluentinc/cp-kafka:5.3.1
        hostname: kafka
        ports:
            - "9092:9092"
        healthcheck:
            test: "nc -z localhost 9092"
            interval: 1s
            retries: 60
        # environment: 
        # networks: 
        #     net:
        #         ipv4_address: 172.28.1.8
        logging:
            driver: none
        depends_on: 
            - zk